import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import './Register.css';

// 학원 코드 자동 생성 함수
// 혼동하기 쉬운 문자 제외: 0(영), O(오), I(아이), 1(일), L(엘)
const generateAcademyCode = () => {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; // 0, O, I, 1, L 제외
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
};

const Register = () => {
  const [formData, setFormData] = useState({
    academy_code: '',
    password: '',
    confirmPassword: '',
    academy_name: '',
    name: '',
    email: '',
    phone: '',
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(false);
  const { register } = useAuth();
  const navigate = useNavigate();

  const handleChange = (e) => {
    const { name, value } = e.target;
    
    // 학원 이름이 입력되면 학원 코드 자동 생성
    if (name === 'academy_name' && value.trim() && !isCodeAutoGenerated) {
      const generatedCode = generateAcademyCode();
      setFormData({
        ...formData,
        academy_name: value,
        academy_code: generatedCode,
      });
      setIsCodeAutoGenerated(true);
    } else {
      setFormData({
        ...formData,
        [name]: value,
      });
      
      // 학원 코드를 수동으로 수정하면 자동 생성 플래그 해제
      if (name === 'academy_code') {
        setIsCodeAutoGenerated(false);
      }
    }
    
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    // 유효성 검증
    if (!formData.academy_code || !formData.password || !formData.academy_name || !formData.name) {
      setError('필수 항목을 모두 입력해주세요.');
      return;
    }

    if (formData.password.length < 6) {
      setError('비밀번호는 최소 6자 이상이어야 합니다.');
      return;
    }

    if (formData.password !== formData.confirmPassword) {
      setError('비밀번호가 일치하지 않습니다.');
      return;
    }

    setLoading(true);

    try {
      const registerData = {
        academy_code: formData.academy_code.trim(),
        password: formData.password,
        academy_name: formData.academy_name.trim(),
        name: formData.name.trim(),
        email: formData.email.trim() || null,
        phone: formData.phone.trim() || null,
      };

      console.log('회원가입 데이터 전송:', { ...registerData, password: '***' });

      const result = await register(registerData);
      
      console.log('회원가입 결과:', result);
      
      if (result && result.success) {
        // 회원가입 성공 시 저장된 학원 코드를 알려주고 로그인 페이지로 이동
        const savedAcademyCode = result.user?.academy_code || result.academy_code || formData.academy_code.toUpperCase();
        alert(`회원가입이 완료되었습니다!\n\n학원 코드: ${savedAcademyCode}\n\n이 코드로 로그인해주세요.`);
        setLoading(false);
        navigate('/login', { replace: true });
      } else {
        // 에러 메시지가 객체인 경우 문자열로 변환
        let errorMsg = '회원가입에 실패했습니다.';
        if (result?.error) {
          if (typeof result.error === 'string') {
            errorMsg = result.error;
          } else if (result.error?.message) {
            errorMsg = result.error.message;
          } else {
            errorMsg = JSON.stringify(result.error);
          }
        }
        console.error('회원가입 실패:', errorMsg);
        setError(errorMsg);
        setLoading(false);
      }
    } catch (err) {
      console.error('회원가입 중 예외 발생:', err);
      const errorMsg = err.message || '회원가입 중 오류가 발생했습니다.';
      setError(errorMsg);
      setLoading(false);
    }
  };

  return (
    <div className="auth-page">
      <div className="auth-container register-container">
        <div className="auth-header">
          <h1>학원 관리 시스템</h1>
          <p>회원가입</p>
        </div>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <div className="error-message">{error}</div>}

          <div className="form-group">
            <label htmlFor="academy_name">
              학원 이름 <span className="required">*</span>
            </label>
            <input
              type="text"
              id="academy_name"
              name="academy_name"
              value={formData.academy_name}
              onChange={handleChange}
              placeholder="학원 이름을 입력하세요"
              required
              autoFocus
              disabled={loading}
            />
            <small className="form-hint">학원 이름을 입력하면 학원 코드가 자동으로 생성됩니다.</small>
          </div>

          <div className="form-group">
            <label htmlFor="academy_code">
              학원 코드 <span className="required">*</span>
              {isCodeAutoGenerated && (
                <span className="auto-generated-badge">자동 생성됨</span>
              )}
            </label>
            <div className="academy-code-input-wrapper">
              <input
                type="text"
                id="academy_code"
                name="academy_code"
                value={formData.academy_code}
                onChange={handleChange}
                placeholder="학원 이름을 입력하면 자동 생성됩니다"
                required
                disabled={loading}
                style={{ textTransform: 'uppercase' }}
                className={isCodeAutoGenerated ? 'auto-generated' : ''}
              />
              <button
                type="button"
                onClick={() => {
                  const newCode = generateAcademyCode();
                  setFormData({ ...formData, academy_code: newCode });
                  setIsCodeAutoGenerated(true);
                }}
                className="btn-regenerate-code"
                disabled={loading}
                title="새 코드 생성"
              >
                🔄
              </button>
            </div>
            <small className="form-hint">
              {isCodeAutoGenerated 
                ? '학원 이름을 입력하면 자동으로 생성됩니다. 필요시 재생성 버튼을 클릭하세요.'
                : '영문 대문자와 숫자 조합 (예: ABC12345) - 학원 이름을 입력하면 자동 생성됩니다'}
            </small>
          </div>

          <div className="form-group">
            <label htmlFor="password">
              비밀번호 <span className="required">*</span>
            </label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="비밀번호를 입력하세요 (최소 6자)"
              required
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="confirmPassword">
              비밀번호 확인 <span className="required">*</span>
            </label>
            <input
              type="password"
              id="confirmPassword"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleChange}
              placeholder="비밀번호를 다시 입력하세요"
              required
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="name">
              관리자 이름 <span className="required">*</span>
            </label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              placeholder="관리자 이름을 입력하세요"
              required
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">이메일 (선택사항)</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="이메일을 입력하세요"
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="phone">연락처 (선택사항)</label>
            <input
              type="tel"
              id="phone"
              name="phone"
              value={formData.phone}
              onChange={handleChange}
              placeholder="연락처를 입력하세요"
              disabled={loading}
            />
          </div>

          <button type="submit" className="btn-primary" disabled={loading}>
            {loading ? '가입 중...' : '회원가입'}
          </button>
        </form>

        <div className="auth-footer">
          <p>
            이미 계정이 있으신가요?{' '}
            <Link to="/login">로그인</Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Register;

