import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollView: {
    flex: 1,
  },
  monthViewContainer: {
    flex: 1,
  },
  // 뷰 토글
  viewToggle: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    margin: 16,
    borderRadius: 8,
    padding: 4,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  toggleButtonActive: {
    backgroundColor: '#9C27B0',
  },
  toggleText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  toggleTextActive: {
    color: '#fff',
  },
  // 헤더
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#F3E5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  headerRight: {
    flexDirection: 'row',
    gap: 12,
  },
  headerButton: {
    padding: 4,
  },
  eventsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#F3E5F5',
  },
  eventsButtonText: {
    fontSize: 12,
    color: '#9C27B0',
    fontWeight: '600',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#F3E5F5',
  },
  addButtonText: {
    fontSize: 14,
    color: '#9C27B0',
    fontWeight: '600',
  },
  // 월간 보기 스타일
  calendarCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  monthNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  monthText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  weekdayHeader: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  weekdayCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  weekdayText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
  },
  sundayText: {
    color: '#f44336',
  },
  saturdayText: {
    color: '#2196F3',
  },
  daysGridScrollView: {
    flex: 1,
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  dayCell: {
    width: '14.28%',
    minHeight: 100,
    padding: 6,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    position: 'relative',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    overflow: 'hidden',
  },
  otherMonthDayCell: {
    backgroundColor: '#f9f9f9',
  },
  selectedDayCell: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#9C27B0',
    borderRadius: 8,
  },
  todayCell: {
    borderWidth: 1,
    borderColor: '#9C27B0',
    borderRadius: 8,
  },
  dayCellTop: {
    width: '100%',
    alignItems: 'flex-start',
    marginBottom: 0,
  },
  weekdayLabel: {
    fontSize: 10,
    color: '#999',
    marginBottom: 2,
    alignSelf: 'flex-start',
  },
  dayText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '400',
    zIndex: 1,
    marginBottom: 0,
  },
  otherMonthText: {
    color: '#ccc',
  },
  selectedDayText: {
    color: '#333',
    fontWeight: 'bold',
  },
  todayText: {
    color: '#9C27B0',
    fontWeight: 'bold',
  },
  dayEventsList: {
    width: '100%',
    marginTop: 0,
    paddingTop: 0,
    flexShrink: 0,
  },
  dayEventItem: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 2,
  },
  dayEventBar: {
    width: 3,
    height: 12,
    backgroundColor: '#9C27B0',
    marginRight: 3,
    borderRadius: 1,
    flexShrink: 0,
  },
  dayEventText: {
    fontSize: 8,
    color: '#333',
    flex: 1,
    lineHeight: 10,
  },
  eventsCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 16,
    marginTop: 0,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  eventsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  eventItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  eventText: {
    flex: 1,
    fontSize: 14,
    color: '#333',
  },
  eventTime: {
    fontSize: 12,
    color: '#666',
    marginRight: 4,
  },
  eventLocation: {
    fontSize: 12,
    color: '#666',
  },
  // 일별 보기 스타일
  dayViewContainer: {
    flex: 1,
  },
  dayViewScrollView: {
    flex: 1,
  },
  dateNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  dateText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  scheduleContainer: {
    backgroundColor: '#fff',
    margin: 16,
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  timeSlot: {
    flexDirection: 'row',
    marginBottom: 16,
    minHeight: 60,
  },
  timeLabel: {
    width: 80,
    paddingRight: 12,
  },
  timeText: {
    fontSize: 12,
    color: '#999',
  },
  eventsColumn: {
    flex: 1,
  },
  eventBlock: {
    backgroundColor: '#F3E5F5',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    position: 'relative',
  },
  deleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 4,
    zIndex: 1,
  },
  deleteButtonText: {
    fontSize: 18,
  },
  eventBlockTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  eventBlockTime: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  eventBlockLocation: {
    fontSize: 12,
    color: '#666',
  },
  noEventText: {
    fontSize: 12,
    color: '#ccc',
    paddingVertical: 8,
  },
  // 모달 스타일
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  closeButton: {
    padding: 4,
  },
  modalScrollView: {
    paddingHorizontal: 20,
  },
  modalSection: {
    marginTop: 20,
  },
  modalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#fff',
  },
  modalInputDisabled: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#f5f5f5',
  },
  modalInputDisabledText: {
    fontSize: 14,
    color: '#333',
  },
  timeRow: {
    flexDirection: 'row',
    marginTop: 20,
  },
  timeSection: {
    flex: 1,
  },
  timePickerSection: {
    marginTop: 20,
  },
  timePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  timePickerHeaderItem: {
    flex: 1,
    alignItems: 'center',
  },
  timePickerHeaderItemActive: {
    // 활성화 상태 스타일
  },
  timePickerDateLabel: {
    fontSize: 12,
    color: '#999',
    marginBottom: 8,
  },
  timePickerTimeDisplay: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#f5f5f5',
  },
  timePickerTimeDisplayActive: {
    backgroundColor: '#E0E0E0',
  },
  timePickerTimeText: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
  },
  timePickerTimeTextActive: {
    color: '#333',
    fontWeight: '600',
  },
  timePickerArrow: {
    paddingHorizontal: 12,
  },
  modalTextArea: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#fff',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  saveButton: {
    backgroundColor: '#9C27B0',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 20,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  // 삭제 확인 모달 스타일
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteModalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    width: '80%',
    maxWidth: 400,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
    textAlign: 'center',
  },
  deleteModalMessage: {
    fontSize: 16,
    color: '#666',
    marginBottom: 24,
    textAlign: 'center',
  },
  deleteModalButtons: {
    flexDirection: 'row',
  },
  deleteModalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  deleteModalCancelButton: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  deleteModalConfirmButton: {
    backgroundColor: '#f44336',
  },
  deleteModalCancelText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  deleteModalConfirmText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
  },
  // 날짜 상세 모달 스타일
  dateDetailModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  dateDetailModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    maxHeight: '80%',
    width: '90%',
    maxWidth: 500,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  dateDetailModalWrapper: {
    width: '100%',
    minHeight: 200,
  },
  dateDetailModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  dateDetailModalWeekday: {
    fontSize: 14,
    color: '#999',
    marginBottom: 4,
  },
  dateDetailModalDate: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  dateDetailCloseButton: {
    padding: 4,
  },
  dateDetailEventsList: {
    maxHeight: 400,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  dateDetailEventsListContent: {
    paddingBottom: 16,
  },
  dateDetailEventItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  dateDetailEventBar: {
    width: 4,
    height: '100%',
    backgroundColor: '#9C27B0',
    marginRight: 12,
    borderRadius: 2,
    minHeight: 50,
  },
  dateDetailEventContent: {
    flex: 1,
  },
  dateDetailEventTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  dateDetailEventTime: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  dateDetailEventLocation: {
    fontSize: 12,
    color: '#999',
  },
  dateDetailDeleteButton: {
    padding: 8,
    marginLeft: 8,
  },
  dateDetailDeleteText: {
    fontSize: 18,
  },
  dateDetailEmptyState: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  dateDetailEmptyText: {
    fontSize: 14,
    color: '#999',
  },
  dateDetailAddButtonContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    backgroundColor: '#fff',
  },
  dateDetailAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#F3E5F5',
  },
  dateDetailAddButtonText: {
    fontSize: 16,
    color: '#9C27B0',
    fontWeight: '600',
  },
  // 시간 선택 모달 스타일
  timePickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  timePickerModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 20,
  },
  timePickerModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  timePickerModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  timePickerCancelButton: {
    padding: 8,
  },
  timePickerCancelText: {
    fontSize: 16,
    color: '#666',
  },
  timePickerConfirmButton: {
    padding: 8,
  },
  timePickerConfirmText: {
    fontSize: 16,
    color: '#9C27B0',
    fontWeight: '600',
  },
  timePickerWheel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 250,
    paddingVertical: 0,
    position: 'relative',
  },
  timePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
    pointerEvents: 'none',
  },
  timePickerOverlayTop: {
    height: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  timePickerOverlayMiddle: {
    height: 50,
    backgroundColor: 'transparent',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e0e0e0',
  },
  timePickerOverlayBottom: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  timePickerColumn: {
    height: 250,
    width: 80,
    position: 'relative',
    zIndex: 0,
  },
  timePickerItem: {
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timePickerItemText: {
    fontSize: 18,
    color: '#ccc',
    opacity: 0.3,
  },
  timePickerItemTextActive: {
    fontSize: 24,
    color: '#333',
    fontWeight: '600',
    opacity: 1,
  },
  timePickerColon: {
    fontSize: 24,
    color: '#333',
    marginHorizontal: 8,
  },
  // 일정 상세 모달 스타일
  eventDetailModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  eventDetailModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '90%',
    maxWidth: 500,
    paddingBottom: 20,
  },
  eventDetailModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  eventDetailModalWeekday: {
    fontSize: 14,
    color: '#999',
    marginBottom: 4,
  },
  eventDetailModalDate: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  eventDetailCloseButton: {
    padding: 4,
  },
  eventDetailContent: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  eventDetailEventBar: {
    width: 4,
    backgroundColor: '#9C27B0',
    borderRadius: 2,
    marginRight: 16,
  },
  eventDetailEventInfo: {
    flex: 1,
  },
  eventDetailEventTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  eventDetailEventTime: {
    fontSize: 18,
    color: '#666',
    marginBottom: 12,
  },
  eventDetailEventLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  eventDetailEventLocationIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  eventDetailEventLocation: {
    fontSize: 16,
    color: '#666',
  },
  eventDetailDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f44336',
  },
  eventDetailDeleteButtonText: {
    fontSize: 16,
    color: '#f44336',
    fontWeight: '600',
  },
  // 다가오는 이벤트 모달 스타일
  upcomingEventsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  upcomingEventsModalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '90%',
    maxWidth: 500,
    maxHeight: '80%',
    paddingBottom: 20,
  },
  upcomingEventsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  upcomingEventsModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  upcomingEventsCloseButton: {
    padding: 4,
  },
  upcomingEventsList: {
    paddingHorizontal: 20,
    paddingTop: 16,
    maxHeight: 400,
  },
  upcomingEventItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  upcomingEventDate: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  upcomingEventDateText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginRight: 4,
  },
  upcomingEventWeekday: {
    fontSize: 14,
    color: '#999',
  },
  upcomingEventContent: {
    marginLeft: 0,
  },
  upcomingEventTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 6,
  },
  upcomingEventDetails: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  upcomingEventTime: {
    fontSize: 14,
    color: '#666',
  },
  upcomingEventLocation: {
    fontSize: 14,
    color: '#666',
  },
  upcomingEventsEmptyState: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  upcomingEventsEmptyText: {
    fontSize: 14,
    color: '#999',
  },
});
